### ISSUE TITLE
couldn't install rcamino on macOS Sierra (10.12.6) on an early 2015 mbp

### ISSUE THREAD

**Issue by lxiao5** [muschellij2/rcamino#1]
The problem seems to have something to do with JAVA.

**# Below is error message. **

./simulation/geometry/substrates/SquashyInflammationSubstrate.java:22: error: package org.omg.CORBA.portable is not visible
import org.omg.CORBA.portable.OutputStream;
                    ^
  (package org.omg.CORBA.portable is declared in module java.corba, which is not in the module graph)
Installation failed: Command failed (1)
Error in neuro_install("rcamino") : 
  Installation failed, please try with upgrade_dependencies = TRUE
Note: ./misc/SphericalPoints.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
make[1]: *** [apps/AddNoise.class] Error 1
make: *** [all] Error 2
ERROR: compilation failed for package ‘rcamino’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rcamino’

**# R Session Info is as follows:**

R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocInstaller_1.26.1

loaded via a namespace (and not attached):
 [1] httr_1.3.1      compiler_3.4.2  R6_2.2.2        tools_3.4.2     withr_2.0.0    
 [6] curl_3.0        memoise_1.1.0   git2r_0.19.0    digest_0.6.12   devtools_1.13.3

**Comment by muschellij2** [comment]
Can you run `java -version` and `javac -version` from the terminal.

Can you try to install `rJava`.  This package has nothing to do with
rcamino, but it may be able to show some errors.

John

**Comment by lxiao5** [comment]
### # This is what I got checking the java versions:

Luos-MacBook-Pro:~ lxiao5$ java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
Luos-MacBook-Pro:~ lxiao5$ javac -version
javac 1.8.0_144
Luos-MacBook-Pro:~ lxiao5$ 

### # I could install rJava but couldn't load it. Below is the error message:

Error: package or namespace load failed for ‘rJava’ in get(Info[i, 1], envir = env):
 lazy-load database '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/R/rJava.rdb' is corrupt
In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1

**Comment by muschellij2** [comment]
Can you run in the terminal:

xcode-select --version



John

**Comment by lxiao5** [comment]
I got:

xcode-select version 2347.

**Comment by muschellij2** [comment]
Can you post the whole log file (including the downloading/unzipping/etc).

John

**Comment by lxiao5** [comment]
Attached is what I got.

[rcamino_install_error.pdf](https://github.com/muschellij2/rcamino/files/1412746/rcamino_install_error.pdf)

**Comment by muschellij2** [comment]
Can you try at the terminal:
R CMD javareconf

and try to install again.

If that doesn't work, can you install rJava again and show me the output.



John

**Comment by muschellij2** [comment]
Also please try to install from the Terminal R and not RStudio as well.

John

**Comment by lxiao5** [comment]
### Below is what I got from the terminal output, which seems to indicate some sort of issue already:

Luos-MacBook-Pro:~ lxiao5$ R CMD javareconf
Java interpreter : /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/bin/java
Java version     : 1.8.0_144
Java home path   : /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home
Java compiler    : /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/javac
Java headers gen.: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/javah
Java archive tool: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/jar
System Java on macOS

trying to compile and link a JNI program 
detected JNI cpp flags    : -I/System/Library/Frameworks/JavaVM.framework/Headers
detected JNI linker flags : -framework JavaVM
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/System/Library/Frameworks/JavaVM.framework/Headers  -I/usr/local/include   -fPIC  -Wall -g -O2  -c conftest.c -o conftest.o
conftest.c:4:5: warning: 'JNI_CreateJavaVM' is deprecated
      [-Wdeprecated-declarations]
    JNI_CreateJavaVM(0, 0, 0);
    ^
/System/Library/Frameworks/JavaVM.framework/Headers/jni.h:1936:39: note: 
      'JNI_CreateJavaVM' has been explicitly marked deprecated here
_JNI_IMPORT_OR_EXPORT_ __attribute__((deprecated)) jint JNICALL
                                      ^
1 warning generated.
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o conftest.so conftest.o -framework JavaVM -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation


JAVA_HOME        : /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home
Java library path: 
JNI cpp flags    : -I/System/Library/Frameworks/JavaVM.framework/Headers
JNI linker flags : -framework JavaVM
Updating Java configuration in /Library/Frameworks/R.framework/Resources
Done.

**Comment by muschellij2** [comment]
That should be OK - please retry rcamino and send output.

John

**Comment by lxiao5** [comment]
I still got the same error trying to install rcamino. Attached
[rJava_load_error.pdf](https://github.com/muschellij2/rcamino/files/1412764/rJava_load_error.pdf)
 is for rJava.

**Comment by muschellij2** [comment]
Please install all of these using RStudio not the R.app.

John

**Comment by muschellij2** [comment]
Check out
https://stackoverflow.com/questions/30738974/rjava-load-error-in-rstudio-r-after-upgrading-to-osx-yosemite


John
