### ISSUE TITLE
ERROR: compilation failed for package 'rcamino'

### ISSUE THREAD

**Issue by ibontama** [muschellij2/rcamino#2]
Hi, 

I am trying to install rcamino in windows and I have these errors:
Thanks, 
Ibon

> source("https://neuroconductor.org/neurocLite.R")
Bioconductor version 3.6 (BiocInstaller 1.28.0), ?biocLite for help
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.6 (BiocInstaller 1.28.0), R 3.4.1 (2017-06-30).
Using neurocLite version: # neurocInstall package version: 0.10.3
> neuro_install('rcamino', release = "stable", release_repo = latest_neuroc_release(release = "stable")) 
Installing package into ‘C:/Users/xx/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
--- Please select a CRAN mirror for use in this session ---
Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘rcamino’
Do you want to attempt to install these from sources?
y/n: y
installing the source package ‘rcamino’

trying URL 'https://neuroconductor.org/releases/latest/stable/src/contrib/rcamino_0.5.5.tar.gz'
Content type 'application/force-download' length 7223735 bytes (6.9 MB)
downloaded 6.9 MB

* installing *source* package 'rcamino' ...
** libs

*** arch - i386
no DLL was created
ERROR: compilation failed for package 'rcamino'
* removing 'C:/Users/ibt827/Documents/R/win-library/3.4/rcamino'

The downloaded source packages are in
        ‘C:\Users\ibt827\AppData\Local\Temp\RtmpQXeSn0\downloaded_packages’
Warning messages:
1: running command '"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\xx\Documents\R\win-library\3.4" C:\Users\xx\AppData\Local\Temp\RtmpQXeSn0/downloaded_packages/rcamino_0.5.5.tar.gz' had status 1 
2: In install.packages(pkgs = repo, repos = c(Neuroconductor = release_repo,  :
  installation of package ‘rcamino’ had non-zero exit status
3: In neuro_install("rcamino", release = "stable", release_repo = latest_neuroc_release(release = "stable")) :
  Package(s): rcamino released binaries/sources were not installed, please try to install with release_repo = "github"
> neuro_install('rcamino', release = "stable", release_repo = "github")
Downloading GitHub repo neuroconductor/rcamino@fb416d2a8ccc80df2af8bf384136ad4803dc36f3
from URL https://api.github.com/repos/neuroconductor/rcamino/zipball/fb416d2a8ccc80df2af8bf384136ad4803dc36f3
Installing rcamino
"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/ibt827/AppData/Local/Temp/RtmpQXeSn0/devtools5c81b94e39/neuroconductor-rcamino-fb416d2" --library="C:/Users/xx/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'rcamino' ...
** libs

*** arch - i386
no DLL was created
ERROR: compilation failed for package 'rcamino'
* removing 'C:/Users/xx/Documents/R/win-library/3.4/rcamino'
Installation failed: Command failed (1)
Error in neuro_install("rcamino", release = "stable", release_repo = "github") : 
  Installation failed, please try with upgrade_dependencies = TRUE
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 15063)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocInstaller_1.28.0

loaded via a namespace (and not attached):
 [1] httr_1.3.1      compiler_3.4.1  R6_2.2.2        tools_3.4.1     withr_2.0.0     curl_2.8.1      memoise_1.1.0   knitr_1.20      digest_0.6.12   devtools_1.13.3

**Comment by muschellij2** [comment]
I don't have a Windows Machine to test on, so I'll have to hold off on any responses.  Do you have Make installed?

**Comment by ibontama** [comment]
Hi John,

Thanks for answering. Yes, I have Make installed. Something else that I
could check?

Thanks,
All the best,
Ibon

2018-03-28 20:52 GMT-04:00 John Muschelli <notifications@github.com>:

**Comment by muschellij2** [comment]
Can you install camino itself http://camino.cs.ucl.ac.uk/index.php?n=Main.Download?

**Comment by ibontama** [comment]
I have this java version. Could be the problem?

java version "1.8.0_144"

Java(TM) SE Runtime Environment (build 1.8.0_144-b01)

Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

2018-03-29 15:29 GMT-04:00 John Muschelli <notifications@github.com>:

**Comment by muschellij2** [comment]
Can you install the dev version?  I made some changes:

```r
devtools::install_github("muschellij2/rcamino")
```

**Comment by ibontama** [comment]
> devtools::install_github("muschellij2/rcamino")
Downloading GitHub repo muschellij2/rcamino@master
from URL https://api.github.com/repos/muschellij2/rcamino/zipball/master
Installing rcamino
Downloading GitHub repo muschellij2/neurobase@master
from URL https://api.github.com/repos/muschellij2/neurobase/zipball/master
Installing neurobase
"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save
--no-restore --quiet CMD INSTALL
"C:/Users/xx/AppData/Local/Temp/RtmpAPXPj5/devtools20f485078ea/muschellij2-neurobase-224ff46"
\
  --library="C:/Users/xx/Documents/R/win-library/3.4" --install-tests

* installing *source* package 'neurobase' ...
** R
** tests
** preparing package for lazy loading
Error : package 'oro.nifti' 0.8.1 was found, but >= 0.9.0 is required by
'neurobase'
ERROR: lazy loading failed for package 'neurobase'
* removing 'C:/Users/xx/Documents/R/win-library/3.4/neurobase'
* restoring previous 'C:/Users/xx/Documents/R/win-library/3.4/neurobase'
Installation failed: Command failed (1)
"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save
--no-restore --quiet CMD INSTALL
"C:/Users/xx/AppData/Local/Temp/RtmpAPXPj5/devtools20f44347c96/muschellij2-rcamino-41c59ec"
\
  --library="C:/Users/xx/Documents/R/win-library/3.4" --install-tests

* installing *source* package 'rcamino' ...
** libs
  running 'src/Makefile.win' ...
C:/PROGRA~1/R/R-34~1.1/bin/x64/Rscript.exe \
-e "utils::unzip('camino.zip')";
cd camino && make clean && make;
rm -f `find . -name "*~"` `find . -name "*\.class"`
javac -classpath . apps/AddNoise.java
.\simulation\geometry\substrates\SquashyInflammationSubstrate.java:22:
error: package org.omg.CORBA.portable is not visible
import org.omg.CORBA.portable.OutputStream;
                    ^
  (package org.omg.CORBA.portable is declared in module java.corba, which
is not in the module graph)
Note: .\misc\SphericalPoints.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
make[1]: *** [apps/AddNoise.class] Error 1
make: *** [all] Error 2
Warning: running command 'make --no-print-directory -f "Makefile.win"' had
status 2
ERROR: compilation failed for package 'rcamino'
* removing 'C:/Users/xx/Documents/R/win-library/3.4/rcamino'
Installation failed: Command failed (1)

2018-03-29 15:48 GMT-04:00 John Muschelli <notifications@github.com>:

**Comment by muschellij2** [comment]
```r
devtools::install_github("muschellij2/oro.nifti")
devtools::install_github("muschellij2/neurobase")
devtools::install_github("muschellij2/rcamino")

**Comment by muschellij2** [comment]
See https://github.com/muschellij2/rcamino/issues/1 for the previous error `R CMD javareconf`

**Comment by ibontama** [comment]
I have rJava installed and now i have this problem


"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save
--no-restore --quiet CMD INSTALL  \

"C:/Users/xx/AppData/Local/Temp/RtmpAPXPj5/devtools20f44ca05875/muschellij2-rcamino-41c59ec"
--library="C:/Users/xx/Documents/R/win-library/3.4" --install-tests

* installing *source* package 'rcamino' ...
** libs
  running 'src/Makefile.win' ...
C:/PROGRA~1/R/R-34~1.1/bin/x64/Rscript.exe \
-e "utils::unzip('camino.zip')";
cd camino && make clean && make;
rm -f `find . -name "*~"` `find . -name "*\.class"`
javac -classpath . apps/AddNoise.java
.\simulation\geometry\substrates\SquashyInflammationSubstrate.java:22:
error: package org.omg.CORBA.portable is not visible
import org.omg.CORBA.portable.OutputStream;
                    ^
  (package org.omg.CORBA.portable is declared in module java.corba, which
is not in the module graph)
Note: .\misc\SphericalPoints.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
make[1]: *** [apps/AddNoise.class] Error 1
make: *** [all] Error 2
Warning: running command 'make --no-print-directory -f "Makefile.win"' had
status 2
ERROR: compilation failed for package 'rcamino'
* removing 'C:/Users/xx/Documents/R/win-library/3.4/rcamino'


2018-03-29 16:27 GMT-04:00 John Muschelli <notifications@github.com>:

**Comment by ibontama** [comment]
John, I tried on other computer and dev version is working.
I will check what is happening on this computer.
Thanks,

2018-03-29 17:35 GMT-04:00 Ibon Tamayo <ibontama@gmail.com>:

**Comment by muschellij2** [comment]
Great to hear.  Closing now as you can install and seems computer-specific. 

Please comment if you figure it out.  From https://stackoverflow.com/questions/34212378/installation-of-rjava, seems to recommend:

```
You don't seem to have JDK installed. You will need at least
```
sudo apt-get install openjdk-7-jdk
```
then re-run
```
sudo R CMD javareconf
```
Make sure you do NOT set JAVA_HOME by hand - it will be detected automatically. You should then see something like this

**Comment by muschellij2** [comment]
I believe this is now fixed.  This was due to CORBA getting removed from JDK 11: https://stackoverflow.com/questions/51710274/is-there-a-replacement-library-for-corba-in-jdk-11
